### ISSUE TITLE
求16.2.x能用的版本

### ISSUE THREAD

**Issue by gdisk** [moshowgame/Navicat_Keygen_Patch#1]
Navicat_Keygen_Patch_v6.3.5.6_By_DFoX

亲测16.1.x完美可用，16.2.x用不了

**Comment by taozuhong** [comment]
欢迎各位体验[**袋鼠数据库工具**](https://www.datatable.online/en/)


[![Workspace](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/a57b7fe8-aea8-4f1c-926e-374e6b03c27b)](https://www.datatable.online/en/)
[![Kangaroo-newlook2](https://github.com/LiJunYi2/navicat-keygen-16V/assets/13451009/1e932afe-e78a-4086-ac73-dfaf6eadb921)](https://www.datatable.online/en/)

**Comment by moshowgame** [comment]
请用最新的17版本拉~！ 最新的crack已就绪
